name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run rust formatter to check for consistency in formatting
      run: cargo fmt --all -- --config format_code_in_doc_comments=true --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Install cargo-deny for license checks
      run: cargo install cargo-deny
    - name: check licenses
      run: cargo deny check licenses
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --all-features